export * from './oyl.tsx'
export * from './leather.tsx'
export * from './phantom.tsx'
export * from './xverse.tsx'
export * from './unisat.tsx'
export * from './wizz.tsx'
export * from './okx.tsx'
export * from './magiceden.tsx'
export * from './orange.tsx'
export * from './lasereyes-logo.tsx'
export * from './tokeo.tsx'

export * from './walletIcon.tsx'
