export const MAINNET = 'mainnet'
export const TESTNET = 'testnet'
export const TESTNET4 = 'testnet4'
export const SIGNET = 'signet'
export const REGTEST = 'regtest'
export const FRACTAL_MAINNET = 'fractal_mainnet'
export const FRACTAL_TESTNET = 'fractal_testnet'
export const OYLNET = 'oylnet'
