export const TEXT_HTML = 'text/html'
export const TEXT_CSS = 'text/css'
export const TEXT_PLAIN = 'text/plain'
export const TEXT_JAVASCRIPT = 'text/javascript'

export const APPLICATION_JSON = 'application/json'
export const APPLICATION_JAVASCRIPT = 'application/javascript'
export const APPLICATION_XML = 'application/xml'
export const APPLICATION_PDF = 'application/pdf'
export const APPLICATION_ZIP = 'application/zip'
export const APPLICATION_GZIP = 'application/gzip'
export const APPLICATION_XHTML_XML = 'application/xhtml+xml'
export const APPLICATION_RSS_XML = 'application/rss+xml'
export const APPLICATION_ATOM_XML = 'application/atom+xml'
export const APPLICATION_FORM_URLENCODED = 'application/x-www-form-urlencoded'
export const APPLICATION_OCTET_STREAM = 'application/octet-stream'

export const IMAGE_JPEG = 'image/jpeg'
export const IMAGE_PNG = 'image/png'
export const IMAGE_GIF = 'image/gif'
export const IMAGE_SVG_XML = 'image/svg+xml'
export const IMAGE_WEBP = 'image/webp'
export const IMAGE_ICON = 'image/x-icon'

export const VIDEO_MP4 = 'video/mp4'
export const VIDEO_WEBM = 'video/webm'
export const VIDEO_OGG = 'video/ogg'

export const AUDIO_MP3 = 'audio/mpeg'
export const AUDIO_WAV = 'audio/wav'
export const AUDIO_OGG = 'audio/ogg'

export const MULTIPART_FORM_DATA = 'multipart/form-data'
